# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x86_64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x86_64)
  Oxygen_app_config = debug_x86_64
endif
ifeq ($(config),release_x86_64)
  Oxygen_app_config = release_x86_64
endif

PROJECTS := Oxygen-app

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Oxygen-app:
ifneq (,$(Oxygen_app_config))
	@echo "==== Building Oxygen-app ($(Oxygen_app_config)) ===="
	@${MAKE} --no-print-directory -C Oxygen-app -f Makefile config=$(Oxygen_app_config)
endif

clean:
	@${MAKE} --no-print-directory -C Oxygen-app -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x86_64"
	@echo "  release_x86_64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Oxygen-app"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"